/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import assignment2_hospitalmodel.Hospital.Hospital;
import assignment2_hospitalmodel.Hospital.HospitalDirectory;
import assignment2_hospitalmodel.locationManagement.City;
import assignment2_hospitalmodel.locationManagement.CityDirectory;
import assignment2_hospitalmodel.locationManagement.Community;
import assignment2_hospitalmodel.locationManagement.House;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ksiec
 */
public class CommunityAdminPanel extends javax.swing.JPanel {

    private Community communities;
    private CityDirectory cities;
    private HospitalDirectory hospitals;
    
    /**
     * Creates new form CommunityAdminPanel
     * @param com
     * @param cd
     * @param hd
     */
    public CommunityAdminPanel(Community com, CityDirectory cd, HospitalDirectory hd) {
        this.communities = com;
        this.cities = cd;
        this.hospitals = hd;
        initComponents();
        populateCommunityTbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        communityTbl = new javax.swing.JTable();
        jLabel52 = new javax.swing.JLabel();
        comSearchBarTxt = new javax.swing.JTextField();
        clearComSearchBtn = new javax.swing.JButton();
        viewComBtn = new javax.swing.JButton();
        deleteComBtn = new javax.swing.JButton();
        comSearchBtn = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        viewComNameTxt = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        viewComCityTxt = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        viewComAddressTxt = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        viewComZipTxt = new javax.swing.JTextField();
        updateComBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        viewHospitalTxt = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        comNameTxt = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        comCityTxt = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        comAddressTxt = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        comZipTxt = new javax.swing.JTextField();
        comSaveBtn1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comHospitalTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(240, 231, 255));
        setMinimumSize(new java.awt.Dimension(1070, 750));
        setPreferredSize(new java.awt.Dimension(1070, 750));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Community Administrator Work Area");

        jTabbedPane1.setBackground(new java.awt.Color(240, 231, 255));

        jPanel9.setBackground(new java.awt.Color(240, 231, 255));

        communityTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "House/Building Address", "Name (if hospital)", "Community Name", "City", "Zip Code"
            }
        ));
        jScrollPane7.setViewportView(communityTbl);

        jScrollPane5.setViewportView(jScrollPane7);

        jLabel52.setText("Search Bar:");

        clearComSearchBtn.setText("Clear Search");
        clearComSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearComSearchBtnActionPerformed(evt);
            }
        });

        viewComBtn.setText("View");
        viewComBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewComBtnActionPerformed(evt);
            }
        });

        deleteComBtn.setText("Delete");
        deleteComBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteComBtnActionPerformed(evt);
            }
        });

        comSearchBtn.setText("Search");
        comSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comSearchBtnActionPerformed(evt);
            }
        });

        jLabel53.setText("Community Name:");

        viewComNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewComNameTxtActionPerformed(evt);
            }
        });

        jLabel54.setText("City:");

        jLabel55.setText("House Address:");

        viewComAddressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewComAddressTxtActionPerformed(evt);
            }
        });

        jLabel56.setText("Zip Code:");

        updateComBtn.setText("Update");
        updateComBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateComBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Hospital Name (if applicable):");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addGap(18, 18, 18)
                        .addComponent(comSearchBarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(comSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearComSearchBtn))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(viewComBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel54)
                                    .addComponent(jLabel55)
                                    .addComponent(jLabel56))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewComAddressTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewComCityTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewComZipTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateComBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(deleteComBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel53)
                                    .addComponent(jLabel2))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(viewComNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewHospitalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(101, 101, 101))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(comSearchBarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearComSearchBtn)
                    .addComponent(comSearchBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewComBtn)
                    .addComponent(deleteComBtn))
                .addGap(57, 57, 57)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(viewComNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(viewHospitalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(viewComAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(viewComCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewComZipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel56))
                .addGap(18, 18, 18)
                .addComponent(updateComBtn)
                .addGap(49, 49, 49))
        );

        jTabbedPane1.addTab("View Communities", jPanel9);

        jPanel10.setBackground(new java.awt.Color(240, 231, 255));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel57.setText("Community Name:");

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel58.setText("City:");

        comCityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comCityTxtActionPerformed(evt);
            }
        });

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel59.setText("House/Building Address:");

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel60.setText("Zip Code:");

        comSaveBtn1.setText("Save");
        comSaveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comSaveBtn1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Add New House/Building or Existing Hospital");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Hospital Name:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comSaveBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel57)
                                .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel60, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel59)
                            .addComponent(jLabel4))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comAddressTxt)
                            .addComponent(comNameTxt)
                            .addComponent(comCityTxt)
                            .addComponent(comZipTxt)
                            .addComponent(comHospitalTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))))
                .addGap(196, 196, 196))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(350, 350, 350))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(comNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comHospitalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(comAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(comZipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(comSaveBtn1)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add to Community", jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comCityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comCityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comCityTxtActionPerformed

    private void comSaveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comSaveBtn1ActionPerformed
        if(comHospitalTxt.getText().equals("")){
            
            
            String name = comNameTxt.getText();
            String city = comCityTxt.getText();
            String address = comAddressTxt.getText();
            String zipCode = comZipTxt.getText();

            City c2 = cities.addNewCity();
            c2.setName(city);
            c2.setZipcode(zipCode);

            Community cm = c2.addNewCommunity();
            cm.setName(name);

            House hs = communities.addNewHouse();
            hs.setAddress(address);
            hs.addCity(c2);
            hs.addToCommunity(cm);

            JOptionPane.showMessageDialog(this, "Added to community.");

            comNameTxt.setText("");
            comCityTxt.setText("");
            comAddressTxt.setText("");
            comZipTxt.setText("");

            populateCommunityTbl();
            
        } else if(comHospitalTxt.getText().chars().count() > 0){
            String name = comNameTxt.getText();
            String hospitalName = comHospitalTxt.getText();
            
            Hospital h = hospitals.getHospitalByName(hospitalName);
            City c1 = cities.getCityByName(h.getCity().getName());
            Community cm = c1.addNewCommunity();
            cm.setName(name);

            h.assignToCommunity(cm);
            
            House hs = h.getHouse();
            hs.addToCommunity(cm);
            hs.setCity(c1);
            
            cm.addHospitalToCommunity(h);
            cm.addHouseToCommunity(hs);
            
            JOptionPane.showMessageDialog(this, "Added to community.");

            comNameTxt.setText("");
            comHospitalTxt.setText("");
            comCityTxt.setText("");
            comAddressTxt.setText("");
            comZipTxt.setText("");

            populateCommunityTbl();

        }
    }//GEN-LAST:event_comSaveBtn1ActionPerformed

    private void clearComSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearComSearchBtnActionPerformed
        String s = ("");
        newCommunityFilter(s);
        comSearchBarTxt.setText("");
    }//GEN-LAST:event_clearComSearchBtnActionPerformed

    private void viewComBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewComBtnActionPerformed
        int selectedRowIndex = communityTbl.getSelectedRow();

        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) communityTbl.getModel();
        House selectedHouse = (House) model.getValueAt(selectedRowIndex, 0);

        viewComNameTxt.setText(String.valueOf(selectedHouse.getCommunity().getName()));
        viewComCityTxt.setText(String.valueOf(selectedHouse.getCity().getName()));
        viewComAddressTxt.setText(String.valueOf(selectedHouse.getAddress()));
        viewComZipTxt.setText(String.valueOf(selectedHouse.getCity().getZipcode()));
        if(selectedHouse.getCommunity().getHospital() != null){
        viewHospitalTxt.setText(String.valueOf(selectedHouse.getCommunity().getHospital().getName()));
        }else if(selectedHouse.getCommunity().getHospital() == null){
            viewHospitalTxt.setText("N/A");
        }
        
    }//GEN-LAST:event_viewComBtnActionPerformed

    private void deleteComBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteComBtnActionPerformed
        int selectedRowIndex = communityTbl.getSelectedRow();

        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) communityTbl.getModel();
        House selectedHouse = (House) model.getValueAt(selectedRowIndex, 0);

        communities.deleteHouse(selectedHouse);

        JOptionPane.showMessageDialog(this, "Selection has been deleted.");

        populateCommunityTbl();
    }//GEN-LAST:event_deleteComBtnActionPerformed

    private void comSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comSearchBtnActionPerformed
        String s = comSearchBarTxt.getText();
        newCommunityFilter(s);
    }//GEN-LAST:event_comSearchBtnActionPerformed

    private void viewComAddressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewComAddressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewComAddressTxtActionPerformed

    private void updateComBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateComBtnActionPerformed
        int selectedRowIndex = communityTbl.getSelectedRow();

        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to update.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) communityTbl.getModel();
        House selectedHouse = (House) model.getValueAt(selectedRowIndex, 0);

        selectedHouse.getCommunity().setName(viewComNameTxt.getText());
        selectedHouse.getCity().setName(viewComCityTxt.getText());
        selectedHouse.getCity().setZipcode(viewComZipTxt.getText());
        selectedHouse.setAddress(viewComAddressTxt.getText());

        JOptionPane.showMessageDialog(this, "Community has been updated.");

        viewComNameTxt.setText("");
        viewHospitalTxt.setText("");
        viewComCityTxt.setText("");
        viewComAddressTxt.setText("");
        viewComZipTxt.setText("");

        populateCommunityTbl();
        
    }//GEN-LAST:event_updateComBtnActionPerformed

    private void viewComNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewComNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewComNameTxtActionPerformed

    private void populateCommunityTbl(){
        DefaultTableModel model = (DefaultTableModel) communityTbl.getModel();
        model.setRowCount(0);
        
        for(House hs : communities.getHouseList()){
        if(hs.getCommunity() != null && hs.getCommunity().getHospital() == null){
            Object[] row = new Object[5];
            row[0] = hs;
            row[1] = ("N/A"); 
            row[2] = hs.getCommunity().getName();
            row[3] = hs.getCity().getName();
            row[4] = hs.getCity().getZipcode();
            
            model.addRow(row);
        }else if(hs.getCommunity() != null && hs.getCommunity().getHospital().getName().chars().count() > 0){
            Object[] row = new Object[5];
            row[0] = hs;
            row[1] = hs.getCommunity().getHospital().getName(); 
            row[2] = hs.getCommunity().getName();
            row[3] = hs.getCity().getName();
            row[4] = hs.getCity().getZipcode();
           
           model.addRow(row); 
        }
        
    }
    }
    
    
    
    private void newCommunityFilter(String s){
        DefaultTableModel modelD = (DefaultTableModel) communityTbl.getModel();
        TableRowSorter<DefaultTableModel> t = new TableRowSorter<>(modelD);
        communityTbl.setRowSorter(t);
        t.setRowFilter(RowFilter.regexFilter(s));
        
    }
    

    public Community getCommunities() {
        return communities;
    }

    public void setCommunities(Community communities) {
        this.communities = communities;
    }

    public CityDirectory getCities() {
        return cities;
    }

    public void setCities(CityDirectory cities) {
        this.cities = cities;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearComSearchBtn;
    private javax.swing.JTextField comAddressTxt;
    private javax.swing.JTextField comCityTxt;
    private javax.swing.JTextField comHospitalTxt;
    private javax.swing.JTextField comNameTxt;
    private javax.swing.JButton comSaveBtn1;
    private javax.swing.JTextField comSearchBarTxt;
    private javax.swing.JButton comSearchBtn;
    private javax.swing.JTextField comZipTxt;
    private javax.swing.JTable communityTbl;
    private javax.swing.JButton deleteComBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton updateComBtn;
    private javax.swing.JTextField viewComAddressTxt;
    private javax.swing.JButton viewComBtn;
    private javax.swing.JTextField viewComCityTxt;
    private javax.swing.JTextField viewComNameTxt;
    private javax.swing.JTextField viewComZipTxt;
    private javax.swing.JTextField viewHospitalTxt;
    // End of variables declaration//GEN-END:variables
}
