/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import assignment2_hospitalmodel.Hospital.HospitalDirectory;
import assignment2_hospitalmodel.Patient.PatientDirectory;
import assignment2_hospitalmodel.doctor.DoctorDirectory;
import assignment2_hospitalmodel.encounter.EncounterHistory;
import assignment2_hospitalmodel.locationManagement.CityDirectory;
import assignment2_hospitalmodel.locationManagement.Community;
import assignment2_hospitalmodel.person.PersonDirectory;
import assignment2_hospitalmodel.system.HospitalSystem;


/**
 *
 * @author ksiec
 */
public class MainJFrame extends javax.swing.JFrame {
    
    HospitalSystem system;
    HospitalDirectory hospitals;
    CityDirectory cities;
    Community communities;
    DoctorDirectory doctors;
    PatientDirectory patients;
    PersonDirectory persons;
    EncounterHistory encounters;

    /**
     * Creates new form MainJFrame2
     */
    public MainJFrame() {
        initComponents();
        system = new HospitalSystem("eHealthCare");
        hospitals = system.getHospitals();
        cities = system.getCities();
        communities = system.getCommunities();
        doctors = system.getDoctors();
        patients = system.getPatients();
        persons = system.getPersons();
        encounters = system.getEncounters();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        selectOption = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        patientBtn = new javax.swing.JToggleButton();
        doctorBtn = new javax.swing.JToggleButton();
        hospitalBtn = new javax.swing.JToggleButton();
        CommunityBtn = new javax.swing.JToggleButton();
        systemAdminBtn = new javax.swing.JToggleButton();
        exitBtn = new javax.swing.JToggleButton();
        workArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1330, 870));
        setSize(new java.awt.Dimension(1330, 870));

        jSplitPane1.setDividerLocation(248);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(1310, 0));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(1310, 0));

        selectOption.setBackground(new java.awt.Color(227, 248, 227));
        selectOption.setMinimumSize(new java.awt.Dimension(240, 590));
        selectOption.setPreferredSize(new java.awt.Dimension(240, 590));
        selectOption.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setText("eHealthCare Roles");
        selectOption.add(jLabel5);
        jLabel5.setBounds(20, 30, 200, 30);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        selectOption.add(jSeparator2);
        jSeparator2.setBounds(0, 70, 250, 20);

        patientBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        patientBtn.setText("Patient");
        patientBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        patientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientBtnActionPerformed(evt);
            }
        });
        selectOption.add(patientBtn);
        patientBtn.setBounds(20, 100, 200, 30);

        doctorBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        doctorBtn.setText("Doctor");
        doctorBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        doctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorBtnActionPerformed(evt);
            }
        });
        selectOption.add(doctorBtn);
        doctorBtn.setBounds(20, 160, 200, 30);

        hospitalBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        hospitalBtn.setText("Hospital Administrator");
        hospitalBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hospitalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalBtnActionPerformed(evt);
            }
        });
        selectOption.add(hospitalBtn);
        hospitalBtn.setBounds(20, 230, 200, 30);

        CommunityBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CommunityBtn.setText("Community Administrator");
        CommunityBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CommunityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunityBtnActionPerformed(evt);
            }
        });
        selectOption.add(CommunityBtn);
        CommunityBtn.setBounds(20, 300, 200, 30);

        systemAdminBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        systemAdminBtn.setText("System Administrator");
        systemAdminBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        systemAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemAdminBtnActionPerformed(evt);
            }
        });
        selectOption.add(systemAdminBtn);
        systemAdminBtn.setBounds(20, 370, 200, 30);

        exitBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        exitBtn.setText("Exit System");
        exitBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        selectOption.add(exitBtn);
        exitBtn.setBounds(20, 440, 200, 30);

        jSplitPane1.setLeftComponent(selectOption);

        workArea.setMinimumSize(new java.awt.Dimension(1075, 0));
        workArea.setPreferredSize(new java.awt.Dimension(1075, 0));
        workArea.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setText("Welcome to eHealthCare");
        workArea.add(jLabel1);
        jLabel1.setBounds(190, 290, 520, 80);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        workArea.add(jSeparator1);
        jSeparator1.setBounds(150, 350, 590, 10);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ksiec\\OneDrive\\Pictures\\App_Background image.png")); // NOI18N
        workArea.add(jLabel2);
        jLabel2.setBounds(0, 0, 1080, 950);

        jSplitPane1.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hospitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalBtnActionPerformed
        HospitalWorkArea hospitalWAPanel = new HospitalWorkArea(hospitals, cities, communities, doctors, patients, persons, encounters);
        jSplitPane1.setRightComponent(hospitalWAPanel);
    }//GEN-LAST:event_hospitalBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void patientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientBtnActionPerformed
        PatientWorkPanel patientWAPanel = new PatientWorkPanel(hospitals, doctors);
        jSplitPane1.setRightComponent(patientWAPanel);
    }//GEN-LAST:event_patientBtnActionPerformed

    private void doctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorBtnActionPerformed
        DoctorWorkPanel doctorWAPanel = new DoctorWorkPanel(patients, doctors, encounters);
        jSplitPane1.setRightComponent(doctorWAPanel);
    }//GEN-LAST:event_doctorBtnActionPerformed

    private void CommunityBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunityBtnActionPerformed
        CommunityAdminPanel communityPanel = new CommunityAdminPanel(communities, cities, hospitals);
        jSplitPane1.setRightComponent(communityPanel);
    }//GEN-LAST:event_CommunityBtnActionPerformed

    private void systemAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemAdminBtnActionPerformed
        SystemAdminPanel systemPanel = new SystemAdminPanel(hospitals, cities, communities, doctors, patients, persons, encounters);
        jSplitPane1.setRightComponent(systemPanel);
    }//GEN-LAST:event_systemAdminBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    
        /* Create and display the form */
        
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CommunityBtn;
    private javax.swing.JToggleButton doctorBtn;
    private javax.swing.JToggleButton exitBtn;
    private javax.swing.JToggleButton hospitalBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToggleButton patientBtn;
    private javax.swing.JPanel selectOption;
    private javax.swing.JToggleButton systemAdminBtn;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables



 public HospitalSystem getSystem() {
        return system;
    }

    public void setSystem(HospitalSystem system) {
        this.system = system;
    }

}
