/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import assignment2_hospitalmodel.Hospital.Hospital;
import assignment2_hospitalmodel.Hospital.HospitalDirectory;
import assignment2_hospitalmodel.doctor.Doctor;
import assignment2_hospitalmodel.doctor.DoctorDirectory;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ksiec
 */
public class PatientWorkPanel extends javax.swing.JPanel {

    HospitalDirectory hospitals;
    DoctorDirectory doctors;
    
    /**
     * Creates new form PatientWorkPanel
     * @param hd
     */
    public PatientWorkPanel(HospitalDirectory hd, DoctorDirectory dd) {
        this.hospitals = hd;
        this.doctors = dd;
        initComponents();
        populateTable();
        populateDocTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        hospitalTbl = new javax.swing.JTable();
        searchTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        clearSearchBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();
        hospitalTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cityTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        zipCodeTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        docTbl = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        docSearchTxt = new javax.swing.JTextField();
        docSearchBtn = new javax.swing.JButton();
        docClearBtn = new javax.swing.JButton();
        viewDocBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        docSpcTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        docNameTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        docHospitalTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        docPhoneTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        docEmailTxt = new javax.swing.JTextField();
        clearViewBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        docCityTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        docHospitalZipTxt = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1070, 850));

        jPanel3.setBackground(new java.awt.Color(209, 230, 252));
        jPanel3.setPreferredSize(new java.awt.Dimension(1070, 800));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Patient Work Area");

        jTabbedPane2.setBackground(new java.awt.Color(209, 230, 252));
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(1070, 850));

        jPanel1.setBackground(new java.awt.Color(209, 230, 252));
        jPanel1.setPreferredSize(new java.awt.Dimension(1070, 800));

        hospitalTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hospital Name", "City", "Zip Code", "Address"
            }
        ));
        jScrollPane2.setViewportView(hospitalTbl);

        jScrollPane3.setViewportView(jScrollPane2);

        searchTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Search Bar:");

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        clearSearchBtn.setText("Clear Search");
        clearSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSearchBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Hopsital Name:");

        viewBtn.setText("View Hospital");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        hospitalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalTxtActionPerformed(evt);
            }
        });

        jLabel4.setText("City:");

        jLabel5.setText("Zip Code:");

        jLabel6.setText("Address:");

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(clearSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(272, 328, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(104, 104, 104))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hospitalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zipCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(clearBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(297, 297, 297))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(searchBtn)
                    .addComponent(clearSearchBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewBtn)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hospitalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(zipCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(clearBtn)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Search for Hospital", jPanel1);

        jPanel2.setBackground(new java.awt.Color(209, 230, 252));
        jPanel2.setPreferredSize(new java.awt.Dimension(1069, 800));

        docTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Specialty", "Name", "Hospital", "City", "Zip Code", "Phone #", "Email"
            }
        ));
        jScrollPane5.setViewportView(docTbl);

        jScrollPane1.setViewportView(jScrollPane5);

        jLabel7.setText("Search Bar:");

        docSearchBtn.setText("Search");
        docSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docSearchBtnActionPerformed(evt);
            }
        });

        docClearBtn.setText("Clear Search");
        docClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docClearBtnActionPerformed(evt);
            }
        });

        viewDocBtn.setText("View Doctor");
        viewDocBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDocBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Specialty:");

        jLabel9.setText("Name:");

        docNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docNameTxtActionPerformed(evt);
            }
        });

        jLabel10.setText("Hospital:");

        jLabel11.setText("Phone #:");

        jLabel12.setText("Email:");

        clearViewBtn.setText("Clear");
        clearViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearViewBtnActionPerformed(evt);
            }
        });

        jLabel13.setText("City:");

        jLabel14.setText("Zip Code:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewDocBtn)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(docSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(docSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(docClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clearViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(docSpcTxt)
                                    .addComponent(docNameTxt)
                                    .addComponent(docPhoneTxt)
                                    .addComponent(docEmailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                                    .addComponent(docCityTxt)
                                    .addComponent(docHospitalZipTxt)
                                    .addComponent(docHospitalTxt))))))
                .addGap(95, 95, 95))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(docSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(docSearchBtn)
                    .addComponent(docClearBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewDocBtn)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(docSpcTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(docNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(docHospitalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(docCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(docHospitalZipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(docPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(docEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearViewBtn)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Search for Doctor", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(451, 451, 451)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clearViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearViewBtnActionPerformed
        docSpcTxt.setText("");
        docNameTxt.setText("");
        docHospitalTxt.setText("");
        docPhoneTxt.setText("");
        docEmailTxt.setText("");
        docCityTxt.setText("");
        docHospitalZipTxt.setText("");
    }//GEN-LAST:event_clearViewBtnActionPerformed

    private void docNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docNameTxtActionPerformed

    private void viewDocBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDocBtnActionPerformed
        int selectedRowIndex = docTbl.getSelectedRow();

        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) docTbl.getModel();
        Doctor selectedDoc = (Doctor) model.getValueAt(selectedRowIndex, 0);

        docSpcTxt.setText(String.valueOf(selectedDoc.getJobTitle()));
        docNameTxt.setText(String.valueOf(selectedDoc.getPerson().getName()));
        docHospitalTxt.setText(String.valueOf(selectedDoc.getHospital().getName()));
        docPhoneTxt.setText(String.valueOf(selectedDoc.getPerson().getPhoneNumber()));
        docEmailTxt.setText(String.valueOf(selectedDoc.getPerson().getEmailAddress()));
        docCityTxt.setText(String.valueOf(selectedDoc.getHospital().getCity().getName()));
        docHospitalZipTxt.setText(String.valueOf(selectedDoc.getHospital().getCity().getZipcode()));
    }//GEN-LAST:event_viewDocBtnActionPerformed

    private void docClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docClearBtnActionPerformed
        String s = ("");
        newDocFilter(s);
        docSearchTxt.setText("");
    }//GEN-LAST:event_docClearBtnActionPerformed

    private void docSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docSearchBtnActionPerformed
        String s = docSearchTxt.getText();
        newDocFilter(s);
    }//GEN-LAST:event_docSearchBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        hospitalTxt.setText("");
        cityTxt.setText("");
        zipCodeTxt.setText("");
        addressTxt.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void hospitalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalTxtActionPerformed

    }//GEN-LAST:event_hospitalTxtActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        int selectedRowIndex = hospitalTbl.getSelectedRow();

        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) hospitalTbl.getModel();
        Hospital selectedHospital = (Hospital) model.getValueAt(selectedRowIndex, 0);

        hospitalTxt.setText(String.valueOf(selectedHospital.getName()));
        cityTxt.setText(String.valueOf(selectedHospital.getCity().getName()));
        zipCodeTxt.setText(String.valueOf(selectedHospital.getCity().getZipcode()));
        addressTxt.setText(String.valueOf(selectedHospital.getHouse().getAddress()));
    }//GEN-LAST:event_viewBtnActionPerformed

    private void clearSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSearchBtnActionPerformed
        String s = ("");
        newFilter(s);
        searchTxtField.setText("");
    }//GEN-LAST:event_clearSearchBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String s = searchTxtField.getText();
        newFilter(s);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void searchTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtFieldActionPerformed
        String s = docSearchTxt.getText();
        newFilter(s);
    }//GEN-LAST:event_searchTxtFieldActionPerformed

    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) hospitalTbl.getModel();
        model.setRowCount(0);
        
        for(Hospital h : hospitals.getHospitals()){
            Object[] row = new Object[4];
            row[0] = h;
            row[1] = h.getCity().getName();
            row[2] = h.getCity().getZipcode();
            row[3] = h.getHouse().getAddress();
            
            model.addRow(row);
        }
       
    }
    
    
    private void populateDocTable(){
        DefaultTableModel model2 = (DefaultTableModel) docTbl.getModel();
        model2.setRowCount(0);
        for(Doctor d : doctors.getDoctorList()){
            Object[] row = new Object[7];
            row[0] = d;
            row[1] = d.getPerson().getName();
            row[2] = d.getHospital().getName();
            row[3] = d.getHospital().getCity().getName();
            row[4] = d.getHospital().getCity().getZipcode();
            row[5] = d.getPerson().getPhoneNumber();
            row[6] = d.getPerson().getEmailAddress();
            
            model2.addRow(row);
        }
        
    }
    
    
    public void newFilter(String s){
        DefaultTableModel model = (DefaultTableModel) hospitalTbl.getModel();
        TableRowSorter<DefaultTableModel> t = new TableRowSorter<DefaultTableModel>(model);
        hospitalTbl.setRowSorter(t);
        t.setRowFilter(RowFilter.regexFilter(s));
        
    }
    
    public void newDocFilter(String s){
        DefaultTableModel model = (DefaultTableModel) docTbl.getModel();
        TableRowSorter<DefaultTableModel> t = new TableRowSorter<DefaultTableModel>(model);
        docTbl.setRowSorter(t);
        t.setRowFilter(RowFilter.regexFilter(s));
        
    }
    
    public HospitalDirectory getHospitals() {
        return hospitals;
    }

    public void setHospitals(HospitalDirectory hospitals) {
        this.hospitals = hospitals;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton clearSearchBtn;
    private javax.swing.JButton clearViewBtn;
    private javax.swing.JTextField docCityTxt;
    private javax.swing.JButton docClearBtn;
    private javax.swing.JTextField docEmailTxt;
    private javax.swing.JTextField docHospitalTxt;
    private javax.swing.JTextField docHospitalZipTxt;
    private javax.swing.JTextField docNameTxt;
    private javax.swing.JTextField docPhoneTxt;
    private javax.swing.JButton docSearchBtn;
    private javax.swing.JTextField docSearchTxt;
    private javax.swing.JTextField docSpcTxt;
    private javax.swing.JTable docTbl;
    private javax.swing.JTable hospitalTbl;
    private javax.swing.JTextField hospitalTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JButton viewBtn;
    private javax.swing.JButton viewDocBtn;
    private javax.swing.JTextField zipCodeTxt;
    // End of variables declaration//GEN-END:variables
}
